import { Invoice } from '../entities/invoice.entity';
import { InvoiceDetail } from '../entities/invoice-detail.entity';

export const DEFAULT_INVOICE: Partial<Invoice> = {
  isCash: false,
  isPaid: false,
  serie: ' ',
  taxInvoice: ' ',
  po: ' ',
  remark: ' ',
  remark1: ' ',
  returnTo: '',
  transfer: 'n/a',
  discount1: 0,
  discount2: 0,
  discount3: 0,
  discount: 0,
  tax: 0,
  freight: 0,
  persen: 0,
  piutang: 0,
  tunai: 0,
  credit: 0,
  debit: 0,
  option: 0,
  cetak: 0,
  cetak1: 0,
  dp: 0,
  voucher: 0,
  kembali: 0,
  ccardNilai: 0,
  jam: 0,
  xkirim: 0,
  kunci: 0,
  point: 0,
  pax: 0,
  postransfer: 0,
  km: 0,
  pawal: 0,
  promoValue: 0,
  promoDiscount: 0,
  promoSales: 0,
  value: 0,
  value1: 0,
  opening: 0,
  rate: 1.0,
  ratep: 1.0,
  pilih: 0,
  mobile: 0,
  fg: 0,
  poAmount: 0,
  expire: 0,
  app: 0,
  zap: 0,
  waste: 0,
  gratis: 0,
  tidak: 0,
  fee: 0,
  inv12: 1,
  noCard: ' ',
  jenisCard: ' ',
  ccardNama: ' ',
  ccardOto: ' ',
  dine: ' ',
  meja: ' ',
  mobileId: ' ',
  sedan: ' ',
  sedanCode: ' ',
  clientId: ' ',
  posId: ' ',
  camId: ' ',
  promog: ' ',
  canvas: '01',
  kode: '04',
  jasa: 'A',
  lain: '',
  tambah: '',
  cap: '',
  ket: '',
  namapc: '',
  scan1: '',
  scan2: '',
  scan3: '',
  scan4: '',
  sj: '',
};

export const DEFAULT_INVOICE_DETAIL: Partial<InvoiceDetail> = {
  qtyOut: 0,
  zQtyOut: 0,
  disc1: 0,
  disc2: 0,
  disc3: 0,
  disc: 0,
  discx: 0,
  accQty: 0,
  accEnt: 0,
  accQtyTransfer: 0,
  factor: 1,
  ivdSplit: 0,
  adjust: 0,
  cost: 0,
  pokok: 0,
  stkppn: 0,
  kirim: 1,
  ven: 0,
  venp: 0,
  ven1: 0,
  venp1: 0,
  inipromo: 0,
  persen: 0,
  qtyResep: 0,
  edit: 0,
  pilih1: 0,
  pilih2: 0,
  po: 0,
  id1: ' ',
  id2: ' ',
  id3: ' ',
  porderId: ' ',
  batch: ' ',
};
