/**
 * Domain Entity - Pure business entity without infrastructure concerns
 */
export class Stock {
  id: string;
  description: string;
  stockGroupId: string | null;
  minimumStock: number;
  maximumStock: number;
  purchasePrice: number;
  costOfGoodsSold: number;
  purchasePriceDollar: number;
  costOfGoodsSoldDollar: number;
  entityId: string | null;
  isService: boolean;
  brandId: string | null;
  size: string | null;
  color: string | null;
  isSuspended: boolean;
  memo: string | null;
  lastDate: Date | null;
  imagePath: string | null;
  isOpenPrice: boolean;
  taxOption: number; // 0 = Tax Free, 1 = Tax, 2 = Non Tax
  serialNumber: string | null;
  rack: string | null;
  copyToSalesInvoice: boolean;
  markupPercentage1: number;
  markupPercentage2: number;
  markupPercentage3: number;
  markupPercentage4: number;
  markupPercentage5: number;
  markupPercentage6: number;
  standardUnit: number;
  miscFlag: number;
  snackFlag: number;
  foodFlag: number;
  computerFlag: number;
  beverageFlag: number;
  minimumStock1: number;
  maximumStock1: number;
  giftDate1: Date | null;
  giftDate2: Date | null;
  giftCode: string | null;
  partNumber1: string | null;
  partNumber2: string | null;
  price11: number;
  price12: number;
  price13: number;
  price21: number;
  price22: number;
  price23: number;
  price31: number;
  price32: number;
  price33: number;
  price41: number;
  price42: number;
  price43: number;
  expireDate: Date | null;
  kitchen1: number;
  kitchen2: number;
  kitchen3: number;
  kitchen4: number;
  kitchen5: number;
  pieces: number;
  roundUp: boolean;
  commission: number;
  fastMoving: boolean;
  selectPriceTags: boolean;
  priceByQuantity: boolean;
  quantity1: number;
  quantity2: number;
  quantity01: number;
  quantity02: number;
  quantity03: number;
  blockIfBelowPurchase: boolean;
  warnIfBelowCost: boolean;
  warnIfBelowPurchasePrice: boolean;
  customField3: string | null;
  customField2: string | null;
  customField4: string | null;
  lastPurchasePrice: number;
  lastPurchasePriceDollar: number;
  sufficientStock: boolean;
  discountPercentage1: number;
  discountPercentage2: number;
  discountPercentage3: number;
  allowShipping: boolean;
  points: number;
  customField5: string | null;
  storeType: string | null;
  isConsignment: boolean;
  totalQuantity: number;
  discountPercentage: number;
  noDiscount: boolean;
  totalOutOfStock: number;
  class01: number;
  class02: number;
  class03: number;
  class04: number;
  class05: number;
  class06: number;
  class07: number;
  class08: number;
  class09: number;
  class10: number;
  memberOnly: boolean;
  expenseCategoryId: string | null;
  fee: number;
  dimension: number;
  selectable: boolean;
  happyHourDiscount: number;
  basePrice: number;
  basePriceDollar: number;
  basePriceDate: Date | null;
  extraFee: number;
  extraFeeDollar: number;
  multiply: boolean;
  commission1: number;
  noTax: boolean;
  purchasePrice1: number;
  purchasePrice1Dollar: number;
  quantity3: number;
  quantity4: number;
  quantity5: number;
  quantity04: number;
  quantity05: number;
  quantity06: number;
  discountPercentage04: number;
  discountPercentage05: number;
  discountPercentage06: number;
  customField6: string | null;
  customField7: string | null;
  quantityManual: boolean;
  skip: boolean;
  enabled: boolean;
  customField9: string | null;
  customField8: string | null;
  credit: boolean;
  customField10: string | null;
  permitLicense: string | null;
  customFieldOdie: string | null;
  customFieldMkes: string | null;
  kitchen6: number;
  kitchen7: number;
  kitchen8: number;
  kitchen9: number;
  kitchen10: number;
  rack2: string | null;
  rack3: string | null;
  rack4: string | null;
  purchaseOrder: boolean;
  taxOption3: number;
  cost3: number;
  margin3: number;
  margin4: number;
  taxOption3a: number;
  cost3a: number;
  margin3a: number;
  margin4a: number;
  weight: number;
  recipe: boolean;
  iPoint: boolean;
  customField50: string | null;
  smallBusiness: boolean;
  customField51: string | null;
  limit: number;
  length: number;
  width: number;
  height: number;
  customField52: string | null;
  customField53: string | null;
  customField53a: string | null;
  coreTaxCode: string | null;
  copyToPurchasing: boolean;
  totalQuantity2: number;
  totalPrice: number;
}

